coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

# This is the configuration on how the codecov report layout will look like in PR's
comment:
  layout: 'header, diff, flags, components'

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        threshold: 1%
        branches:
          - '!main'
  individual_components:
    - component_id: ibm-products
      name: ibm-products
      paths:
        - ../packages/ibm-products
    - component_id: ibm-products-web-components
      name: ibm-products-web-components
      paths:
        - ../packages/ibm-products-web-components

flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 1%
      - type: patch
        target: 80%
  individual_flags:
    - name: exclude_deprecated #custom flag name to view the project coverage without deprecated components
      paths:
        - '../packages/ibm-products/src/components/**/*.deprecated.test.js' #fill in your own path. Note, accepts globs, not regexes
        - '../packages/ibm-products/src/components/**/*.deprecated.test.ts' #fill in your own path. Note, accepts globs, not regexes
      carryforward: true
      statuses:
        - type: project
          target: 20%
        - type: patch
          target: 100%
